name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
          
      - name: Run tests with pytest
        run: |
          pytest

      - name: Run the Kohonen SOM script
        run: |
          python kohonen.py

      - name: Archive generated images
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: generated-images
          path: |
            images/small
            images/large
